### ISSUE TITLE
Git branch name should be correct on CI

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle-enterprise-build-config-samples#109]
Many CI systems checkout the git project in a detached `HEAD` state leading the branch name to be tagged as `HEAD`.
[Here is an example](https://ge.spring.io/s/vrsotpyyb7xz6#info) from the spring-authorization-server project.

Each CI system has a unique way of passing the branch name as an environment variable. We should try to capture this as best as possible since `HEAD` is not very useful information.

For example on Jenkins, the branch name is set as the environment variable `BRANCH_NAME`.

One proposal is to try to capture the environment variable as a preference, and use the git status as a backup.

let's discuss possible solutions as well as the differences in setting this variable on Ci.

**Comment by jthurne** [comment]
I like this idea. We could fall back to the branch provided by CI only if we get HEAD back from inspecting the git repo directly.

Implementing this and preserving configuration cache compatibility may be a little tricky in the CCUD Gradle plugin, but it should be doable.

Getting the branch from Jenkins is straightforward, but for TeamCity, it may be a little trickier. See [Branch-related Parameters](https://www.jetbrains.com/help/teamcity/predefined-build-parameters.html#Branch-Related+Parameters).  I haven't looked at other CI systems yet.

**Comment by etiennestuder** [comment]
I would only do it for Jenkins for now. It's the most common CI tool used by our customers.
