### ISSUE TITLE
Add `BUILD_JVM` version as custom value

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle-enterprise-build-config-samples#158]
Add the build's JVM version to the build scan as a custom value. `BUILD_JVM` is a possible value key.

The goal is to identify cache misses that would be caused by a different JVM version so we should capture all the parts of the version that are used in fingerprinting.

We should capture all parts of the key that are use for fingerprint for Maven in Maven builds and all the parts that are used for fingerprintin Gradle builds.

**Comment by etiennestuder** [comment]
@runningcode I believe what you suggest is already shown in the build scan comparison by default when the differences in the JVMs are always causing cache misses.

I'll close for now, but we can discuss further when you are back.

@facewindu Feel free to leave your thoughts on this issue.

**Comment by facewindu** [comment]
Yes, the infrastructure comparison already shows this
![image](https://user-images.githubusercontent.com/5922961/149726643-38fc4db2-44f7-4b6a-af56-d39f25919f5b.png)
I believe this is enough ?

**Comment by etiennestuder** [comment]
@facewindu I meant the inputs comparison showing a message when the JVM is different in a way that leads to full cache misses.

**Comment by facewindu** [comment]
Currentlfy, and for Maven only, when the java class version or the JVM vendor differ, we display
```
The compared builds used a different version or implementation of Java, which causes the inputs for every task to be different.

Goal outputs built when using one Java version cannot be reused when using a different version.
```

That's it.
But the actual JVM version value is already shown in the infrastructure comparison, so I don't see why capturing it as a custom value makes it better.

**Comment by etiennestuder** [comment]
That's the message I had in mind. Thanks.

**Comment by runningcode** [comment]
I did not capture this in the ticket but another goal of this issue was to make builds searchable by all builds which are using a compatible JVM. 
This is helpful for teams doing cross version builds and tests. 
The spring team tags the JVM version to their builds since they do many cross version tests.

While not explicitly described in this ticket, having the toolchain version used for compilation might also be useful as a custom value for specific tasks.

I agree with closing this ticket for now.

**Comment by alextu** [comment]
I agree that the Infrastructure view is just a partial view and it should be great to have the JDK infos on the task level without the need to set custom values. (specially since toolchain will become stable soon)
