### ISSUE TITLE
Use SLF4J logger instead of DefaultLog

### ISSUE THREAD

**Issue by guylabs** [gradle/gradle-enterprise-build-config-samples#164]
In the latest Maven nightly version the `DefaultLog` class [has been renamed](https://github.com/apache/maven/commit/c3962c1a6c0b40abbfb12740253437f6431b234b#diff-08e7da438372645395143b0c54c0b672b7a63abb27b2539e012bf0770edc9ff5).

This makes [nightly tests fail](https://builds.gradle.org/buildConfiguration/Enterprise_Release_Component_CommonCustomUserDataMavenExtension_CrossVersionNightly_MavenLatestNightlyLinux?mode=builds#all-projects) as we use the `DefaultLog` class here https://github.com/gradle/gradle-enterprise-build-config-samples/blob/d389428132f95a713eaaafdf2c6d43c81bde84fb/common-custom-user-data-maven-extension/src/main/java/com/gradle/GroovyScriptUserData.java#L46

We propose to use the SLF4J logger instead as this is stable, but this would mean that some users might have issues as this is a breaking change as the API of the `DefaultLog` is different.

**Comment by etiennestuder** [comment]
Can you please also ask @marcphilipp for review. See also my question [here](https://github.com/gradle/gradle-enterprise-build-config-samples/pull/165#issuecomment-941918289).

**Comment by marcphilipp** [comment]
I'm also in favor of #166.
