### ISSUE TITLE
Generate custom links in CCUD Mvn plugin once GE server URL is fully configured

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle-enterprise-build-config-samples#193]
Similar to what has been done for Gradle [here](https://github.com/gradle/gradle-enterprise-build-config-samples/pull/192).

**Comment by bigdaz** [comment]
My testing was unable to expose any issue with build scan search links generated by the CCUD Maven extension.

This fits with the comment here: https://github.com/gradle/gradle-enterprise-build-config-samples/pull/192#issuecomment-962905469
