### ISSUE TITLE
Set the user name when available on CI

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle-enterprise-build-config-samples#210]
On CI systems such as Github Actions, it tells your who triggers the workflow via an [env var called `GITHUB_ACTOR`](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables)

If you do the equivalent of: 
```kotlin
System.setProperty("user.name", System.getenv("GITHUB_ACTOR"))
```

This will set the user name on the build scan to the person that triggered the workflow, then the build scans dashboard will reflect the person that actually triggered the build, even for CI builds.

**Comment by etiennestuder** [comment]
Interesting.

This can be achieved today by using this [hook](https://docs.gradle.com/enterprise/gradle-plugin/#obfuscating_identifying_data) provided by the Gradle Enterprise plugin. Though primarily meant for obfuscation, it can also be used to change the username to anything else, for example to the Github actor.

There is also the [Gradle Plugin for Github Actions](https://github.com/eskatos/gradle-github-actions-plugin) which already captures the actor as a custom value.

I'll add something to our internal board to further investigate capturing _who_ triggered a build in CI environments.
