### ISSUE TITLE
RfE: Custom set project name for multi-module / multi-project Maven builds

### ISSUE THREAD

**Issue by ascheman** [gradle/gradle-enterprise-build-config-samples#32]
We do have typical builds with `mvn -am -pl <project list>`: Several modules from a multi-module build would be build then including their dependent modules. For this case it would be hard to derive a proper project name. In multi-module builds we do have many entries in the scan list, all with the same top level project name. From my point of view a custom name would be great (e.g., something like `-Dscan.build.name=...`).

**Comment by etiennestuder** [comment]
Interesting idea. For now, the solution is to use a custom value to define the build/project name.
