### ISSUE TITLE
Fix groovy "leftovers"

### ISSUE THREAD

**Issue by TobiX** [gradle/gradle-enterprise-build-config-samples#36]
Seems there was a string forgotten while converting from Groovy to Java:

https://github.com/gradle/gradle-enterprise-build-config-samples/blob/cb2e1ca751ffef07fb96026e48ee3b5c2a6659fc/common-custom-user-data-maven-extension/src/main/java/com/gradle/CustomUserData.java#L235

**Comment by etiennestuder** [comment]
Thanks Tobias. Fixed via [this commit](https://github.com/gradle/gradle-enterprise-build-config-samples/commit/4998f33c43704689bf70d9389d03f0c82a2ee967). It will be available once we do the next release of this extension.
