### ISSUE TITLE
Add line ending normalization to Kotlin Maven caching sample

### ISSUE THREAD

**Issue by erichaagdev** [gradle/gradle-enterprise-build-config-samples#568]
We should also check that the Java and other goals already have this enabled.

**Comment by tylerbertrand** [comment]
https://github.com/gradle/gradle-enterprise-build-config-samples/pull/716

**Comment by tylerbertrand** [comment]
> We should also check that the Java and other goals already have this enabled.

In `java-project`, running a build, changing `App.java` line endings from `LF` to `CRLF`, then running a second build results in `compiler:compile` [coming from cache](https://ge.solutions-team.gradle.com/s/ng273rckyi6ps/timeline?details=pgvm4ufsaf4s2).

Additionally, the [Ignoring Line Endings section of the GE extension manual](https://docs.gradle.com/enterprise/maven-extension/#ignoring_line_endings) states that "The Maven extension normalizes line endings in source files when computing the Build Cache key for compile or testCompile goals of the [maven-compiler-plugin](https://docs.gradle.com/enterprise/maven-extension/#maven_compiler_plugin)."
