### ISSUE TITLE
Tag Android Studio version

### ISSUE THREAD

**Issue by rallat** [gradle/gradle-enterprise-build-config-samples#7]
Is it possible to get the Android studio version to add it as a tag?
Thanks

**Comment by marcphilipp** [comment]
Could you please check if it's passed as a system property?

**Comment by rallat** [comment]
It seems like it is not passed and Google has an issue opened to fix that https://issuetracker.google.com/issues/152941155

**Comment by runningcode** [comment]
Looks like this will be added in Android Studio 4.1 as `android.injected.studio.version`.
To add this to a buildscan you can do:
```
if (project.hasProperty('android.injected.studio.version')) {
  buildScan.value 'AS Version', project.getProperty('android.injected.studio.version')
} 
```
