### ISSUE TITLE
Small error in custom user data script (NODE_NAME vs. JOB_NAME)

### ISSUE THREAD

**Issue by TobiX** [gradle/gradle-enterprise-build-config-samples#9]
Wrong variable is used here:

https://github.com/gradle/gradle-enterprise-build-config-samples/blob/99609d2702f09913cf1f9eadc6592c920fd3bc2f/common-custom-user-data-scripts/maven-common-custom-user-data.groovy#L67-L69

**Comment by marcphilipp** [comment]
Good catch!
