### ISSUE TITLE
Undeclared system property reads in common-custom-user-data-gradle-plugin

### ISSUE THREAD

**Issue by ALikhachev** [gradle/gradle-enterprise-build-config-samples#92]
The Gradle plugin makes direct system property reads that may cause configuration cache issues, for example `idea.version` if executing build from IDEA with the plugin applied.

The plugin is used in [Kotlin build](https://github.com/JetBrains/kotlin/blob/b3bb033fe40a50246e5258a4a94313958a6636a5/settings.gradle#L44) and prevents configuration cache adoption alongside with Gradle Enterprise.

**Comment by etiennestuder** [comment]
Agreed. We will get to it soon.

**Comment by jthurne** [comment]
Fixed in the Common Custom User Data Gradle Plugin version 1.4, which we released today.
